### ISSUE TITLE
Cannot build and run tests in EVM

### ISSUE THREAD

**Issue by platocrat** [ethereum-optimism/Waffle-ERC20-Example#12]
## Issue
After successfully using Node v10 to install the deps, Step 4 of the README "Setup" fails with the following ambiguous error:

<img width="874" alt="Screen Shot 2020-12-23 at 10 04 18 PM" src="https://user-images.githubusercontent.com/37757724/103059459-ce9a4a00-456a-11eb-803e-1e8f1d6f4d9c.png">

## Steps to reproduce
1. Follow steps 1 - 3 in the README's "Setup" section
2. After step 3, run `yarn all:evm` in step 4
3. See error

**Comment by platocrat** [comment]
### Post-hoc Note
CTL + F'ing for "engine" shows up nowhere in the repo's files except for the `yarn.lock` file

**Comment by tina1998612** [comment]
same error, I'm using Ubuntu 18.04

**Comment by platocrat** [comment]
Yeah, this repo is out of done and don’t think it will be updated due to the team prioritizing their core

**Comment by leoxs22** [comment]
Is there any workaround for this? I would keep the issue open otherwise

**Comment by tynes** [comment]
See this repo for an updated example: https://github.com/ethereum-optimism/optimism-tutorial
